[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Pong"
authors = [{name = "Peter"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: GNU Public License v3 or later (GPLv3+)"]
dynamic = ["version", "description"]
